create extension if not exists "pgcrypto";

create type public.prompt_access as enum ('Free', 'Premium');
create type public.prompt_status as enum ('Draft', 'Published', 'Archived');
create type public.prompt_category as enum ('Students', 'Teachers', 'Business', 'Social Media', 'Freelancers', 'Writing', 'Productivity', 'Marketing', 'Research', 'Email');
create type public.user_role as enum ('user', 'admin');
create type public.subscription_plan as enum ('Free', 'Founding');
create type public.subscription_status as enum ('free', 'pending', 'active', 'past_due', 'cancelled', 'expired');
create type public.prompt_request_status as enum ('open', 'reviewing', 'completed', 'rejected');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text check (char_length(full_name) <= 120),
  mobile_number text check (mobile_number is null or mobile_number ~ '^\+639[0-9]{9}$'),
  role public.user_role not null default 'user',
  preferred_category public.prompt_category,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  plan public.subscription_plan not null default 'Free',
  status public.subscription_status not null default 'free',
  provider text check (provider is null or provider = 'xendit'),
  provider_subscription_id text unique,
  provider_checkout_id text unique,
  provider_customer_id text,
  provider_payment_token_id text,
  provider_last_cycle_id text,
  provider_last_cycle_number integer check (provider_last_cycle_number is null or provider_last_cycle_number > 0),
  provider_event_id text,
  provider_event_created_at timestamptz,
  current_period_start timestamptz,
  current_period_end timestamptz,
  access_until timestamptz,
  grace_until timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.prompts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  category public.prompt_category not null,
  access public.prompt_access not null default 'Free',
  status public.prompt_status not null default 'Published',
  purpose text not null check (char_length(purpose) between 1 and 500),
  prompt text not null check (char_length(prompt) between 1 and 12000),
  best_for text not null check (char_length(best_for) between 1 and 500),
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.prompt_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category public.prompt_category not null,
  title text not null check (char_length(title) between 3 and 160),
  details text not null check (char_length(details) between 10 and 3000),
  status public.prompt_request_status not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.billing_checkout_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  reference_id text not null unique,
  provider_session_id text unique,
  provider_customer_id text,
  provider_payment_id text,
  provider_payment_token_id text,
  provider_recurring_plan_id text unique,
  payment_succeeded boolean not null default false,
  status text not null default 'creating' check (status in ('creating', 'pending', 'paid', 'plan_created', 'cancelled', 'failed')),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.billing_events (
  webhook_id text primary key,
  event_type text not null,
  business_id text not null,
  payload jsonb not null,
  status text not null default 'processing' check (status in ('processing', 'completed', 'failed', 'ignored')),
  processing_error text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create index prompts_status_access_idx on public.prompts (status, access);
create index subscriptions_user_status_idx on public.subscriptions (user_id, status);
create index subscriptions_access_until_idx on public.subscriptions (access_until);
create index prompt_requests_user_status_idx on public.prompt_requests (user_id, status);
create index billing_checkout_user_created_idx on public.billing_checkout_sessions (user_id, created_at desc);
create index billing_events_created_idx on public.billing_events (created_at desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

create or replace function public.has_active_entitlement()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_admin() or exists (
    select 1
    from public.subscriptions
    where user_id = (select auth.uid())
      and plan = 'Founding'
      and (
        access_until > now()
        or (status = 'past_due' and grace_until > now())
      )
  );
$$;

create or replace function public.get_prompt_catalog()
returns table (
  id bigint,
  title text,
  category public.prompt_category,
  access public.prompt_access,
  status public.prompt_status,
  purpose text,
  prompt text,
  best_for text,
  tags text[],
  created_at timestamptz,
  updated_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    p.id,
    p.title,
    p.category,
    p.access,
    p.status,
    p.purpose,
    case
      when p.access = 'Free' or public.has_active_entitlement() then p.prompt
      else null
    end,
    p.best_for,
    p.tags,
    p.created_at,
    p.updated_at
  from public.prompts p
  where p.status = 'Published'
  order by p.id;
$$;

create or replace function public.admin_update_user_access(
  target_user_id uuid,
  next_role public.user_role,
  next_plan public.subscription_plan,
  next_status public.subscription_status,
  next_access_until timestamptz
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  if target_user_id = (select auth.uid()) and next_role <> 'admin' then
    raise exception 'You cannot remove your own admin access';
  end if;

  if next_role <> 'admin'
    and exists (select 1 from public.profiles where id = target_user_id and role = 'admin')
    and (select count(*) from public.profiles where role = 'admin') <= 1 then
    raise exception 'At least one administrator is required';
  end if;

  update public.profiles
  set role = next_role, updated_at = now()
  where id = target_user_id;

  if not found then
    raise exception 'User profile not found';
  end if;

  insert into public.subscriptions (user_id, plan, status, access_until, updated_at)
  values (target_user_id, next_plan, next_status, next_access_until, now())
  on conflict (user_id) do update
  set plan = excluded.plan,
      status = excluded.status,
      access_until = excluded.access_until,
      updated_at = excluded.updated_at;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, left(new.raw_user_meta_data->>'full_name', 120))
  on conflict (id) do nothing;

  insert into public.subscriptions (user_id, plan, status)
  values (new.id, 'Free', 'free')
  on conflict (user_id) do nothing;

  return new;
end;
$$;

create or replace function public.enforce_open_prompt_request_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(new.user_id::text, 0));

  if new.status in ('open', 'reviewing')
    and (
      select count(*)
      from public.prompt_requests
      where user_id = new.user_id and status in ('open', 'reviewing')
    ) >= 3 then
    raise exception 'At most three open or reviewing prompt requests are allowed';
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create trigger enforce_prompt_request_limit
before insert on public.prompt_requests
for each row execute function public.enforce_open_prompt_request_limit();

alter table public.profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.prompts enable row level security;
alter table public.prompt_requests enable row level security;
alter table public.billing_checkout_sessions enable row level security;
alter table public.billing_events enable row level security;

create policy "Users read own profile" on public.profiles
for select to authenticated
using (id = (select auth.uid()) or public.is_admin());

create policy "Users update safe profile fields" on public.profiles
for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy "Admins manage profiles" on public.profiles
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Users read own subscription" on public.subscriptions
for select to authenticated
using (user_id = (select auth.uid()) or public.is_admin());

create policy "Admins manage subscriptions" on public.subscriptions
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins manage prompts" on public.prompts
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Users read own requests" on public.prompt_requests
for select to authenticated
using (user_id = (select auth.uid()) or public.is_admin());

create policy "Entitled users create requests" on public.prompt_requests
for insert to authenticated
with check (user_id = (select auth.uid()) and public.has_active_entitlement());

create policy "Admins manage requests" on public.prompt_requests
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

revoke all on table public.prompts from anon, authenticated;
revoke update on table public.profiles from authenticated;
grant update (full_name, mobile_number, preferred_category, updated_at) on table public.profiles to authenticated;
grant execute on function public.get_prompt_catalog() to anon, authenticated;
grant execute on function public.admin_update_user_access(uuid, public.user_role, public.subscription_plan, public.subscription_status, timestamptz) to authenticated;
revoke all on table public.billing_checkout_sessions from anon, authenticated;
revoke all on table public.billing_events from anon, authenticated;
